### PR TITLE
format scss

### PR DESCRIPTION
**Pull request by oxinabox**
I just ran it through an autoformatter; set indent to 2 spaces.

Also I deleted the out of date comment from the top.

### CODE REVIEW

**Comment by oxinabox** [comment]
@Roger-luo we said we would use ColPrac.
That means you should not merge my PRs.  :slightly_smiling_face: 

https://github.com/SciML/ColPrac#reviewing-approving-and-merging-prs

> *   PRs by people with merge rights should not be merged by people other than the author (just approved).

**Comment by Roger-luo** [comment]
Ah sorry, I'll just let you merge it afterward then!

**Comment by Roger-luo** [comment]
so IIUC only approved PRs will be merged by the author? or approved PRs can be merged by other people? @oxinabox

**Comment by oxinabox** [comment]
If the author has merge rights, then only the author should merge.
But anyone can, and someone must, approve before merging.

This let's the author make any final tweaks or respond to any last minor comments.


If the author doesn't have merge rights then generally approve and merge should be done as a single step.

**Pull request merged**
